name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn
      run: yarn --network-concurrency 1
    - name: linter checks
      run: yarn lint
    - name: prettify diff
      run: yarn prettify:diff
    - name: tests
      run: yarn test
      env:
        CI: true
    - name: build
      run: yarn build
    - name: check i18n dupes
      run: yarn i18n-check-dupes

